[general]
import = [
	"~/.config/alacritty/themes/one_dark.toml"
]
[font]

normal.family = "UbuntuMono Nerd Font Mono"
bold.family = "UbuntuMono Nerd Font Mono"
italic.family = "UbuntuMono Nerd Font Mono"
bold_italic.family = "UbuntuMono Nerd Font Mono"

size = 14.0

[terminal.shell]
program = "/bin/zsh"
